/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NugetRouteImport } from './routes/nuget'
import { Route as BestPracticesRouteImport } from './routes/best-practices'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const NugetRoute = NugetRouteImport.update({
  id: '/nuget',
  path: '/nuget',
  getParentRoute: () => rootRouteImport,
} as any)
const BestPracticesRoute = BestPracticesRouteImport.update({
  id: '/best-practices',
  path: '/best-practices',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/best-practices': typeof BestPracticesRoute
  '/nuget': typeof NugetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/best-practices': typeof BestPracticesRoute
  '/nuget': typeof NugetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/best-practices': typeof BestPracticesRoute
  '/nuget': typeof NugetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/architecture' | '/best-practices' | '/nuget'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/architecture' | '/best-practices' | '/nuget'
  id: '__root__' | '/' | '/architecture' | '/best-practices' | '/nuget'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BestPracticesRoute: typeof BestPracticesRoute
  NugetRoute: typeof NugetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nuget': {
      id: '/nuget'
      path: '/nuget'
      fullPath: '/nuget'
      preLoaderRoute: typeof NugetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-practices': {
      id: '/best-practices'
      path: '/best-practices'
      fullPath: '/best-practices'
      preLoaderRoute: typeof BestPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  BestPracticesRoute: BestPracticesRoute,
  NugetRoute: NugetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
